# Generated by Django 5.2 on 2025-06-09 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0005_user_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_id', models.IntegerField()),
                ('stuff_name', models.CharField(max_length=30)),
                ('stuff_desc', models.CharField(max_length=257)),
                ('photo', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rate', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
