# Generated by Django 5.2 on 2025-06-09 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0006_stuff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stuff',
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
