# Generated by Django 5.2 on 2025-05-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0002_rename_product_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
    ]
